"""Baan Sawan: reference villa page using the V6 shell and V4 composition."""
import json
import re
from html import escape

ARROW='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="M4 12h15M13 5l7 7-7 7"/></svg>'
def icon(paths):
    return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+paths+'</svg>'

def contact(label,intent,source,cls='text-link'):
    return f'<button type="button" class="{cls}" data-contact="{intent}" data-villa="Baan Sawan" data-source="baansawan-{source}">{label}{ARROW}</button>'

def render_villa(home,root):
    pics=[dict(src=f'assets/baansawan/{i:02}.webp',caption=caption) for i,caption in enumerate([
        'Baan Sawan au crépuscule','Façade mer et piscine à débordement','Séjour ouvert sur la mer','Cuisine et salle à manger','Suite principale','Salle de bains','Cour tropicale et jardin','Vue d’ensemble sur les hauteurs de Lamai'],1)]
    interior=[
        dict(id='essentiel',name='Essentiel',image='interieur-carte-blanche.webp',subtitle='Équipée, non meublée',status='Inclus',lead='Une villa achevée, avec sa cuisine, ses salles d’eau et ses équipements. Le mobilier et la décoration restent à votre choix.',specs=[['Cuisine','Plan en quartz, électroménager intégré et îlot central ouvert sur le séjour.'],['Salles d’eau','Cinq salles d’eau équipées ; choix des revêtements, vasques et robinetteries précisés avec l’architecte.'],['Confort','Climatisation par zone, toiture isolée et points d’éclairage fonctionnels.'],['Finitions','Sols, murs et menuiseries selon le descriptif de la villa. Les références et matériaux définitifs seront précisés dans la proposition.'],['Non compris','Mobilier, luminaires décoratifs, textiles et décoration.']]),
        dict(id='eveil',name='Éveil des sens',image='interieur-eveil-des-sens.webp',subtitle='Meublée et prête à vivre',status='Sur devis',lead='La base Essentiel complétée par un ensemble de mobilier, de luminaires et de textiles coordonnés.',specs=[['Base incluse','Les équipements et finitions de la gamme Essentiel.'],['Mobilier','Aménagement du séjour, de l’espace repas et des cinq chambres. Implantations et dimensions adaptées aux plans de Baan Sawan.'],['Textiles','Rideaux, tapis et textiles de chambre coordonnés.'],['Luminaires','Éclairage décoratif sélectionné pour les pièces de vie et les chambres.'],['Matières et finitions','Palette de bois, tissus et finitions présentée avec la sélection du mobilier. Références et quantités sur devis.']]),
        dict(id='art-de-vivre',name='Art de vivre',image='interieur-art-de-vivre.webp',subtitle='Un intérieur signature',status='Sur devis',lead='Une composition plus complète, avec des aménagements dessinés pour la villa et une attention particulière aux matières et à la lumière.',specs=[['Base incluse','Le mobilier, les textiles et les luminaires de la gamme Éveil des sens.'],['Aménagements','Menuiseries et rangements sur mesure selon le projet retenu.'],['Décoration','Sélection d’objets, d’art mural et de végétaux pour compléter les espaces.'],['Matières et lumière','Finitions coordonnées, choix de matières et éclairages d’ambiance étudiés avec l’architecte.'],['Équipements complémentaires','Options de confort définies avec vous et détaillées dans le devis.']])
    ]
    exterior=[
        dict(id='essentiel',name='Essentiel',image='jardin-carte-blanche.webp',subtitle='Piscine, terrasse et terrain préparé',status='Inclus',lead='La piscine à débordement et la terrasse font déjà partie de Baan Sawan. Le terrain est préparé et engazonné.',specs=[['Piscine','Piscine à débordement de 10 × 4 m, profondeur 1,40 m, filtration au sel et éclairage LED submergé, selon le descriptif actuel.'],['Terrasse','Terrasse en continuité du séjour, avec revêtements et finitions précisés dans le projet architectural.'],['Terrain','Terrain préparé, nivelé et engazonné.'],['Non compris','Mobilier extérieur, plantations complémentaires, cuisine d’été et éclairage paysager d’ambiance.']]),
        dict(id='horizon',name='Horizon',image='jardin-eclosion.webp',subtitle='Un jardin tropical composé',status='Sur devis',lead='Des plantations et des cheminements organisent le jardin autour de la piscine et prolongent les espaces de vie.',specs=[['Base incluse','La piscine à débordement, la terrasse et le terrain préparé de la gamme Essentiel.'],['Végétation','Plantations en pleine terre, essences tropicales et massifs structurés.'],['Cheminements','Allées et circulations intégrées au plan paysager.'],['Matières et entretien','Choix des revêtements, essences et besoins d’arrosage adaptés au terrain ; détail et quantités sur devis.']]),
        dict(id='art-de-vivre',name='Art de vivre',image='jardin-art-de-vivre.webp',subtitle='Des extérieurs signature',status='Sur devis',lead='Un aménagement paysager plus complet, pensé pour recevoir et profiter des extérieurs tout au long de la journée.',specs=[['Base incluse','Les plantations et cheminements de la gamme Horizon.'],['Composition paysagère','Une végétation plus généreuse et des espaces extérieurs aménagés selon votre usage.'],['Éclairage','Mise en lumière du jardin, des circulations et des espaces de détente.'],['Cuisine d’été','Implantation, équipements et finitions définis selon le projet.'],['Mobilier extérieur','Sélection coordonnée aux terrasses et espaces de réception ; références et quantités sur devis.']])
    ]
    features=[
        ('Piscine privée à débordement','10 × 4 m, profondeur 1,40 m, filtration au sel et éclairage LED submergé.',False,'<path d="M3 18q3-3 6 0t6 0t6 0M3 22q3-3 6 0t6 0t6 0M7 15V5a2 2 0 0 1 4 0m3 10V5a2 2 0 0 1 4 0M7 8h7M7 12h7"/>'),
        ('Cuisine entièrement équipée','Plan en quartz, électroménager intégré, îlot central et ouverture sur le séjour et la terrasse.',False,'<rect x="3" y="9" width="18" height="12" rx="1"/><path d="M2 9h20M9 9v12M15 9V5a2 2 0 0 1 4 0M6 13v3M13 13h5"/>'),
        ('Toiture tropicale isolée','Bois exotique et tuiles naturelles, isolation thermique renforcée et gestion des eaux pluviales.',False,'<path d="m2 11 10-8 10 8M5 11v10h14V11M8 12l4-3 4 3M8 16h8"/>'),
        ('Climatisation par zone','Système inverter, contrôle via application et programmation indépendante pour les différentes pièces.',False,'<rect x="3" y="3" width="18" height="8" rx="2"/><path d="M6 8h12M7 15c-3 2 3 3 0 6m5-6c-3 2 3 3 0 6m5-6c-3 2 3 3 0 6"/>'),
        ('Aménagement paysager','Des plantations et des cheminements jusqu’à une composition tropicale plus complète.',True,'<path d="M12 22V10M12 16C3 16 3 10 3 6c5 0 9 2 9 8M12 11c0-6 4-9 9-9 0 6-2 10-9 10M7 22h10"/>'),
        ('Mobilier & décoration','Du mobilier principal à un intérieur signature, choisissez le niveau d’aménagement qui vous correspond.',True,'<path d="M5 12V7a3 3 0 0 1 3-3h8a3 3 0 0 1 3 3v5M5 12a2 2 0 0 0-4 0v7h22v-7a2 2 0 0 0-4 0v3H5v-3ZM4 19v3m16-3v3"/>')
    ]
    hero=f'''<div class="villa-opening"><section class="baan-hero" aria-labelledby="villa-title">
      <img src="assets/baansawan/01.webp" alt="Baan Sawan au crépuscule, sa piscine à débordement face à la mer" width="1672" height="941" fetchpriority="high" loading="eager">
      <div class="baan-hero-grid"><div class="baan-hero-copy"><h1 id="villa-title">Baan<br><em>Sawan</em></h1>
      <p>Sur les hauteurs de Lamai, une villa de cinq chambres ouverte sur une vue mer panoramique.</p>
      <div class="baan-hero-actions"><a class="btn btn-light" href="#personnalisation">Personnaliser Baan Sawan{ARROW}</a>{contact('Recevoir la brochure','brochure','hero')}</div></div>
      <aside class="baan-commercial" aria-label="Prix et modalités"><span>À partir de</span><p>805 000 €<sup>*</sup></p><small>Configuration Essentiel</small><div><strong>Paiement flexible</strong>Virement bancaire ou cryptomonnaies, selon les modalités du projet.</div></aside></div>
      </section><section class="baan-facts" aria-label="Caractéristiques de Baan Sawan"><div>'''+''.join(f'<div><strong>{v}</strong><span>{label}</span></div>' for v,label in [('5','Chambres'),('5','Salles d’eau'),('252 m²','Habitables'),('604 m²','Parcelle'),('12–18 mois','Construction*')])+'''</div></section></div>'''
    gallery='''<section class="section baan-gallery" id="galerie"><div class="section-heading"><h2>Baan Sawan,<br><em>la maison du paradis.</em></h2><p class="section-lead">Cinq chambres pour recevoir ses proches, des pièces de vie ouvertes sur la mer et une cour tropicale qui préserve l’intimité. La terrasse et la piscine prolongent naturellement la maison.</p></div><div class="baan-gallery-grid">'''
    for n in [1,2,6,7]:
        p=pics[n];gallery+=f'<button type="button" class="baan-photo" data-photo="{n}" aria-label="Agrandir : {escape(p["caption"])}"><img src="{p["src"]}" alt="{escape(p["caption"])}" loading="lazy" decoding="async"><span>{p["caption"]}</span><span class="photo-expand" aria-hidden="true">{ARROW}</span></button>'
    gallery+=f'''</div><div class="baan-gallery-bottom"><p>Visuels d’intention non contractuels.</p><button type="button" class="text-link" data-photo="0">Voir les 8 photos{ARROW}</button></div><div class="baan-plans"><p>Plan d’implantation, surfaces détaillées et plans cotés disponibles dans la brochure.</p>{contact('Recevoir les plans et la brochure','brochure','plans')}</div></section>'''
    prestations='''<section class="baan-features"><div class="section"><div class="section-heading"><h2>Des prestations pensées<br><em>pour votre confort.</em></h2><p class="section-lead">La piscine, la cuisine et les équipements essentiels sont inclus. Le mobilier, la décoration et le paysage évoluent selon la configuration choisie.</p></div><div class="baan-feature-grid">'''
    for title,body,option,paths in features:
        prestations+=f'<article class="baan-feature"><div class="baan-feature-top">{icon(paths)}<span class="{"option" if option else "included"}">{"En option" if option else "Inclus"}</span></div><h3>{title}</h3><p>{body}</p></article>'
    prestations+='</div><p class="baan-note">Prestations indicatives, à confirmer dans le descriptif propre à la villa.</p></div></section>'
    config='''<section class="baan-config" id="personnalisation"><div class="section"><div class="section-heading"><h2>Faites-en<br><em>votre maison.</em></h2><p class="section-lead">Choisissez une gamme pour l’intérieur et une autre pour les extérieurs. Votre sélection sera reprise dans votre demande d’estimation.</p></div>'''
    for key,label,options in [('interior','L’intérieur',interior),('garden','Les extérieurs',exterior)]:
        config+=f'<fieldset class="baan-config-group"><legend>{label}</legend><div class="baan-config-grid">'
        for i,o in enumerate(options):
            config+=f'''<article class="baan-option"><label><input type="radio" name="{key}" value="{o['id']}" {'checked' if i==0 else ''}><span class="baan-option-card"><img src="assets/{o['image']}" alt="Ambiance {o['name']} — {label.lower()}" loading="lazy" decoding="async"><span class="baan-option-copy"><span class="baan-option-status">{o['status']}<span class="baan-radio" aria-hidden="true"></span></span><strong>{o['name']}</strong><span>{o['subtitle']}</span></span></span></label><button type="button" class="baan-option-detail" data-detail-group="{key}" data-detail-id="{o['id']}" aria-label="Voir le détail : {o['name']}, {label.lower()}">Voir le détail{ARROW}</button></article>'''
        config+='</div></fieldset>'
    config+=f'''<div class="baan-config-summary"><div><p id="baan-selection" role="status" aria-live="polite">Intérieur Essentiel · Extérieurs Essentiel</p><p class="baan-note">Options chiffrées sur devis, en complément du prix de la villa.</p></div><button class="btn btn-light" type="button" id="baan-estimate">Recevoir mon estimation{ARROW}</button></div><p class="baan-note">Visuels d’ambiance non contractuels. Matériaux, références et prestations définitives à valider avec l’architecte.</p><noscript><p>Pour recevoir une proposition, écrivez-nous à <a href="mailto:contact@latitudesamui.com">contact@latitudesamui.com</a>.</p></noscript></div></section>'''
    car=icon('<path d="m4 10 2-6h12l2 6M3 10h18v9H3zM6 19v2m12-2v2M6 14h1m10 0h1"/>')
    location='''<section class="section baan-location" id="emplacement"><div><h2>Les hauteurs de Lamai,<br><em>près de l’essentiel.</em></h2><p class="section-lead">Un environnement ouvert sur la mer, à proximité des plages, des commerces et de la vie locale.</p><ul class="baan-distances">'''
    for place,minutes in [('Plage de Lamai',4),('Hin Ta & Hin Yai',5),('Marché Hua Thanon',7),('Supermarché Lotus',10),('École internationale',18),('Hôpital Bangkok Samui',20),('Aéroport international',22)]:
        location+=f'<li>{car}<span>{place}</span><strong>{minutes} min*</strong></li>'
    location+='''</ul><p class="baan-note">* Temps indicatifs en voiture issus de la présentation provisoire, à confirmer selon la localisation définitive et la circulation.</p></div><div class="baan-map-wrap"><div class="baan-map" id="baan-map"><div class="baan-map-cover" id="baan-map-cover">'''+icon('<path d="M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/>')+'''<h3>Baan <em>Sawan</em></h3><p>Lamai · Koh Samui</p><button type="button" class="btn btn-light" id="baan-map-open">Explorer la carte'''+ARROW+'''</button><p id="baan-map-status" role="status"></p></div></div><div class="baan-map-caption"><span>Emplacement provisoire</span><a href="https://maps.google.com/maps?q=9.4512,100.0412" target="_blank" rel="noopener">Ouvrir dans Google Maps ↗</a></div></div></section>'''
    closing=re.search(r'<section class="closing" id="contact">.*?</section>',home,re.S).group()
    closing=closing.replace('Votre île<br>vous <em>attend.</em>','Découvrons Baan Sawan<br><em>ensemble.</em>').replace('Un lieu de vie, une résidence secondaire ou un nouveau chapitre. Parlons de ce qui vous amène à Samui.','Sur place à Koh Samui ou à distance en vidéo, prenons le temps de découvrir la villa et de répondre à vos questions.')
    closing=re.sub(r'<button.*?</button>',contact('Organiser une visite','visit','closing','btn btn-light'),closing,flags=re.S)
    footnote='''<div class="baan-disclaimer"><p>* Prix de départ en configuration Essentiel : villa équipée, non meublée. Mobilier, décoration et aménagements paysagers complémentaires en option. Le délai indicatif de 12 à 18 mois court à compter du démarrage effectif du chantier et dépend notamment des autorisations et des options retenues.</p></div>'''
    dialogs='''<dialog class="baan-lightbox" id="baan-lightbox" aria-label="Photos de Baan Sawan"><button type="button" class="dialog-close" data-close aria-label="Fermer la galerie">×</button><figure><img id="baan-lightbox-image" alt=""><figcaption id="baan-lightbox-caption" aria-live="polite"></figcaption></figure><div class="baan-lightbox-controls"><button type="button" id="baan-prev" aria-label="Photo précédente">←</button><span id="baan-photo-count" aria-live="polite"></span><button type="button" id="baan-next" aria-label="Photo suivante">→</button></div></dialog><dialog class="baan-detail" id="baan-detail" aria-labelledby="baan-detail-title"><button class="dialog-close" type="button" data-close aria-label="Fermer le détail">×</button><div id="baan-detail-content"></div></dialog>'''
    data=dict(villa='Baan Sawan',photos=pics,interior=interior,garden=exterior)
    page=re.sub(r'<main id="main">.*?</main>',lambda _:'<main id="main">'+hero+gallery+prestations+config+location+closing+'</main>'+dialogs,home,flags=re.S)
    page=page.replace('<footer class="home-footer">',footnote+'<footer class="home-footer">')
    page=page.replace('data-page="index"','data-page="villa-baansawan"').replace('class="has-photo-hero v6"','class="has-photo-hero v6 baan-page"')
    page=page.replace('href="../v5/en/index.html"','href="../v5/en/villa-baansawan.html"')
    page=page.replace('<script defer src="js/hero.js"></script>','').replace('href="assets/hero-01.jpg" fetchpriority="high"','href="assets/baansawan/01.webp" fetchpriority="high"')
    page=re.sub(r'<title>.*?</title>','<title>Baan Sawan — Villa 5 chambres à Lamai | Latitude Samui</title>',page)
    for name,value in [('description','Baan Sawan : cinq chambres, 252 m² habitables et une piscine à débordement sur les hauteurs de Lamai. Découvrez et personnalisez votre villa.'),('og:description','Baan Sawan, villa de cinq chambres avec vue mer panoramique à Lamai.'),('og:title','Baan Sawan — Latitude Samui'),('og:image','assets/baansawan/01.webp')]:
        page=re.sub(r'(<meta (?:name|property)="'+name+r'" content=")[^"]*',lambda m:m[1]+value,page)
    page=page.replace('</head>','<link rel="stylesheet" href="css/villa.css"><script defer src="js/villa.js"></script></head>')
    page=page.replace('</body>','<script type="application/json" id="baan-data">'+json.dumps(data,ensure_ascii=False).replace('<','\\u003c')+'</script></body>')
    return page
