"""Editorial content for both languages. Imported by build.py."""
def editorial_pages(g):
    t=g['t']; image=g['image']; heading=g['heading']; link=g['link']; cta=g['cta']; contact=g['contact']; hero=g['pagehero']; ARROW=g['ARROW']
    pages=[]
    def add(slug,title,description,content,photo=True): pages.append((slug,title,description,content,photo))
    def split(photo,eyebrow,title,body,extra='',reverse=False):
        return f'<section class="editorial-split {"reverse" if reverse else ""}"><div class="editorial-image">{image(photo,"")}</div><div class="editorial-copy"><p class="eyebrow">{eyebrow}</p><h2>{title}</h2>{body}{extra}</div></section>'
    def para(*pairs): return ''.join('<p>'+t(*p)+'</p>' for p in pairs)

    approach=hero(t('Notre philosophie','Our philosophy'),t('Moins de projets.<br><em>Plus d’attention.</em>','Fewer projects.<br><em>More attention.</em>'),t('Une collection volontairement limitée, une équipe impliquée et le souci de bien faire, jusque dans les détails.','A deliberately limited collection, an involved team and care for getting things right, down to the details.'),'approach.webp')
    approach+=f'<section class="section intro-section"><h2>{t("Le beau a du sens<br>quand il se <em>vit bien.</em>","Beauty matters most<br>when it <em>feels right.</em>")}</h2><div class="intro-copy">'+para(('Chaque villa part d’un terrain, d’une orientation et d’un mode de vie. Nous recherchons des espaces fluides, une relation naturelle avec l’extérieur et des choix cohérents avec le climat tropical.','Each villa begins with a plot, an orientation and a way of life. We look for flowing spaces, a natural relationship with the outdoors and choices that suit the tropical climate.'),('La personnalisation vient ensuite donner à la maison votre caractère. Des options lisibles, pensées comme un ensemble, pour garder une vision claire du projet et de son budget.','Personalisation then gives the home your character. Clear options, designed as a whole, help maintain a clear view of the project and its budget.'))+'</div></section>'
    approach+=split('construction.webp',t('Construire directement','Building directly'),t('Un lien direct.<br><em>Une exécution suivie.</em>','A direct relationship.<br><em>Attentive follow-through.</em>'),para(('Nous coordonnons le développement des villas et le suivi des chantiers avec les équipes et partenaires locaux. Cette organisation permet de relier les plans, les décisions et leur réalisation.','We coordinate villa development and construction follow-up with local teams and partners. This approach connects the plans, the decisions and their execution.'),('Architectes, ingénieurs, entreprises et avocats interviennent dans leurs domaines respectifs. Notre rôle : garder un fil conducteur clair pour le futur propriétaire.','Architects, engineers, contractors and lawyers work within their respective areas of expertise. Our role is to keep a clear thread for the future owner.')),link(t('Découvrir l’équipe','Meet the team'),'equipe.html'))
    approach+=f'<section class="section" id="collections">{heading(t("Les trois collections","The three collections"),t("Même exigence.<br><em>Trois façons d’habiter.</em>","The same care.<br><em>Three ways to feel at home.</em>"),t("La base architecturale reste la même. C’est l’aménagement intérieur qui évolue, de la villa équipée à une composition complète.","The architectural foundation stays the same. The interiors evolve, from an equipped villa to a complete composition."))}{g["collections_intro"]()}<div class="collection-descriptions">'+''.join(f'<article><h3>{name}</h3><p>{t(*desc)}</p></article>' for name,pic,sub,desc in g['COLLECTIONS'])+f'</div><p class="fine-print">{t("Les équipements détaillés et le chiffrage des options sont définis dans la proposition propre à chaque villa.","Detailed equipment specifications and option pricing are defined in each villa’s proposal.")}</p>{link(t("Composer votre villa","Compose your villa"),"villas.html")}</section>'
    approach+=split('jardin-art-de-vivre.webp',t('Les extérieurs','Outdoor spaces'),t('Un jardin<br><em>à votre mesure.</em>','A garden<br><em>that feels like you.</em>'),para(('Carte Blanche pose la base : un terrain préparé et engazonné. Éclosion apporte les plantations et les cheminements. Art de Vivre imagine une composition extérieure plus complète.','Carte Blanche provides the foundation: a prepared and turfed plot. Éclosion adds planting and paths. Art de Vivre brings a more complete outdoor composition.'),('La collection intérieure et l’approche paysagère se choisissent indépendamment. Vous pouvez privilégier le jardin, l’atmosphère de la maison ou les deux.','The interior collection and landscaping approach are chosen independently. You can focus on the garden, the atmosphere indoors or both.')),reverse=True)+cta()
    add('notre-approche',t('Notre approche','Our approach'),t('Une collection limitée, une présence locale et trois collections d’aménagement intérieur.','A limited collection, a local presence and three interior collections.'),approach)

    island=hero(t('Vivre à Koh Samui','Life in Koh Samui'),t('Changer d’horizon.<br><em>Garder ses repères.</em>','A different horizon.<br><em>A familiar comfort.</em>'),t('Une île que l’on découvre pour ses plages, et que l’on choisit pour la vie qu’elle permet.','An island you discover for its beaches, and choose for the life it makes possible.'),'samui.webp')
    island+=f'<section class="section intro-section"><h2>{t("Le quotidien,<br>en version <em>insulaire.</em>","Everyday life,<br>with an <em>island rhythm.</em>")}</h2><div class="intro-copy">'+para(('Koh Samui laisse de la place à plusieurs rythmes de vie : les marchés et la cuisine locale, les restaurants internationaux, le sport, la mer et les quartiers résidentiels plus calmes.','Koh Samui leaves room for many rhythms of life: markets and local food, international restaurants, sport, the sea and quieter residential neighbourhoods.'),('S’y installer se prépare aussi concrètement. Écoles, santé, déplacements, connexion internet : nous vous invitons à regarder l’île à travers vos habitudes, pas seulement vos vacances.','Moving here also takes practical preparation. Schools, healthcare, transport and internet access: we encourage you to view the island through your everyday habits, not just your holidays.'))+'</div></section>'
    cards=[('gastronomy.webp','À table, face à la mer','A table by the sea','Cuisine thaïlandaise, marchés et belles tables. De quoi changer d’adresse sans perdre le goût des choses simples.','Thai food, markets and memorable tables. Plenty of variety without losing the pleasure of simple things.'),('wellness.webp','Du temps pour soi','Time for yourself','Yoga, boxe thaïlandaise, salles de sport, soins ou baignade. L’extérieur retrouve une place dans votre journée.','Yoga, Thai boxing, gyms, treatments or a swim. Outdoor life becomes part of your day again.'),('family.webp','Trouver son équilibre','Find your balance','Pour une vie de famille, le choix du quartier se réfléchit avec celui de l’école, des activités et des services de santé.','For family life, choosing a neighbourhood goes hand in hand with schools, activities and healthcare.'),('work.webp','Travailler autrement','A different working day','Pour télétravailler, vérifiez la connexion et l’espace de travail du logement. Le cadre fait le reste.','For remote work, check the connection and workspace of the home. The surroundings do the rest.')]
    island+='<section class="section lifestyle-grid">'+''.join(f'<article>{image(pic,t(fr,en))}<div><p class="eyebrow">0{i+1} · {t("Le quotidien","Everyday life")}</p><h3>{t(fr,en)}</h3><p>{t(dfr,den)}</p></div></article>' for i,(pic,fr,en,dfr,den) in enumerate(cards))+'</section>'
    places=[('Lamai','Plage, vie locale et collines résidentielles. Le secteur de nos villas Sabai, Suk, Jai et Baan Sawan.','Beach, island life and residential hills. Home to our Sabai, Suk, Jai and Baan Sawan villas.'),('Thong Krut','Le sud de l’île, les villages de pêcheurs et un rythme plus discret. Le cadre de notre prochain programme.','The island’s south, fishing villages and a quieter pace. The setting for our upcoming development.'),('Bophut','Autour de Fisherman’s Village, des restaurants et des services. Notre bureau se trouve dans ce secteur.','Around Fisherman’s Village, restaurants and everyday services. Our office is located in this area.'),('Maenam & Plai Laem','D’autres atmosphères au nord de l’île, à découvrir pour mieux comprendre ce qui vous correspond.','Different settings in the north of the island, worth exploring to understand what suits you.')]
    island+=f'<section class="section dark-section">{heading(t("Choisir son quartier","Choose your neighbourhood"),t("Une ambiance,<br><em>pas seulement une adresse.</em>","An atmosphere,<br><em>more than an address.</em>"))}<div class="places-grid">'+''.join(f'<article><h3>{name}</h3><p>{t(fr,en)}</p></article>' for name,fr,en in places)+f'</div>{link(t("Découvrir nos projets","Explore our projects"),"villas.html","text-link on-dark")}</section>{cta()}'
    add('koh-samui',t('Vivre à Koh Samui','Life in Koh Samui'),t('Le quotidien à Koh Samui : quartiers, nature, gastronomie, famille et travail à distance.','Everyday life in Koh Samui: neighbourhoods, nature, food, family and remote work.'),island)

    team=hero(t('L’équipe Latitude','The Latitude team'),t('Des personnes.<br><em>Pas une succession<br>d’intermédiaires.</em>','Real people.<br><em>A direct<br>relationship.</em>'),t('Trois expertises complémentaires réunies autour d’une même vision du projet et de la relation avec chaque propriétaire.','Three complementary areas of expertise with a shared view of each project and the relationship with every owner.'))
    people=[('Sébastien','Direction & stratégie','Leadership & strategy','Entrepreneur expérimenté, Sébastien pilote la stratégie, les partenariats et le développement de Latitude Samui. Il coordonne la relation commerciale et les décisions qui donnent au projet sa direction.','An experienced entrepreneur, Sébastien leads Latitude Samui’s strategy, partnerships and development. He coordinates the commercial relationship and the decisions that give each project its direction.','Vision, partenariats, relation client.','Vision, partnerships, client relationships.'),('Laurent','Construction & terrain','Construction & operations','Professionnel du bâtiment installé à Koh Samui, Laurent supervise les chantiers, les équipes locales et la qualité d’exécution. Il relie les plans et les choix de finition à la réalité quotidienne du terrain.','A construction professional based in Koh Samui, Laurent supervises building sites, local teams and workmanship. He connects plans and finishing choices to the daily realities on site.','Coordination, chantier, qualité.','Coordination, construction, quality.'),('Benoît','Digital & finance','Digital & finance','Formé en finance d’entreprise et en informatique, Benoît supervise l’écosystème numérique, le marketing et les parcours clients. Il coordonne le suivi financier et les solutions de paiement avec les prestataires spécialisés.','With a background in corporate finance and computing, Benoît oversees the digital ecosystem, marketing and client experience. He coordinates financial follow-up and payment solutions with specialist providers.','Digital, parcours client, finance.','Digital, client experience, finance.')]
    team+='<section class="section people-list">'+''.join(f'<article><span class="person-number">0{i+1}</span><div><p class="eyebrow">{t(fr,en)}</p><h2>{name}</h2></div><div><p>{t(dfr,den)}</p><p class="person-focus">{t(efr,een)}</p></div></article>' for i,(name,fr,en,dfr,den,efr,een) in enumerate(people))+'</section>'
    team+=split('construction.webp',t('Autour de l’équipe','Around the team'),t('Des compétences<br><em>qui se complètent.</em>','Expertise<br><em>that works together.</em>'),para(('Chaque projet associe les métiers dont il a besoin : architecture, ingénierie, construction, aménagement et conseil juridique. Les responsabilités sont définies avec les partenaires concernés.','Each project brings together the skills it needs: architecture, engineering, construction, interior design and legal advice. Responsibilities are defined with the relevant partners.'),('Pour vous, l’objectif reste simple : savoir qui suit votre projet et à qui poser votre prochaine question.','For you, the goal is simple: knowing who is following your project and whom to ask your next question.')),link(t('Comprendre notre accompagnement','Understand our approach'),'parcours.html'))+cta()
    add('equipe',t('L’équipe','The team'),t('Sébastien, Laurent et Benoît : trois expertises, des responsabilités claires.','Sébastien, Laurent and Benoît: three areas of expertise, clear responsibilities.'),team,False)

    journey=hero(t('Votre parcours d’achat','Your buying journey'),t('Un nouveau chapitre.<br><em>Des étapes claires.</em>','A new chapter.<br><em>Clear steps.</em>'),t('Du premier échange à la remise des clés, une relation suivie et des décisions que vous pouvez comprendre.','From our first conversation to receiving the keys, a continuing relationship and decisions you can understand.'))
    detail=[('Nous échangeons sur votre usage, vos attentes, votre budget et votre calendrier. Une résidence principale, une maison de vacances ou un projet locatif ne se préparent pas de la même façon.','We discuss your intended use, expectations, budget and timeline. A primary residence, holiday home and rental project each call for a different approach.','À préciser : votre façon de vivre la villa.','To clarify: how you want to use the villa.'),('La visite permet de comprendre la parcelle, l’orientation, les accès et l’environnement. Vous êtes à distance ? Nous pouvons organiser un échange vidéo pour présenter le projet et répondre à vos questions.','A visit helps you understand the plot, orientation, access and surroundings. If you are abroad, we can arrange a video conversation to present the project and answer your questions.','À regarder : le terrain autant que la maison.','To consider: the plot as much as the house.'),('Avant tout engagement, les modalités d’acquisition et les documents du projet sont examinés avec les professionnels compétents. Les avocats présentent les options adaptées à votre situation et les vérifications à mener.','Before any commitment, acquisition terms and project documents are reviewed with the appropriate professionals. Lawyers explain the options suited to your circumstances and the checks to carry out.','À clarifier : droits, contrats, coûts et calendrier.','To clarify: rights, contracts, costs and timing.'),('Le descriptif, les collections choisies et l’échéancier sont définis pour votre villa. Pendant le chantier, des points d’avancement et des photos permettent de suivre les étapes et les décisions.','Specifications, chosen collections and the payment schedule are defined for your villa. During construction, progress updates and photos help you follow the stages and decisions.','À suivre : avancement, choix et validation des étapes.','To follow: progress, choices and stage approvals.'),('La réception permet de parcourir la villa et d’en vérifier les prestations selon les documents convenus. Les besoins d’entretien, de piscine, de jardin ou de gestion peuvent ensuite être organisés avec les partenaires locaux.','The handover gives you the opportunity to inspect the villa and its features against the agreed documents. Maintenance, pool, garden or management needs can then be arranged with local partners.','À organiser : votre arrivée et la vie de la maison.','To organise: your arrival and the daily life of the home.')]
    journey+='<section class="section journey-list">'+''.join(f'<article><div class="journey-index">0{i+1}</div><div><p class="eyebrow">{t(dfr,den)}</p><h2>{t(fr,en)}</h2></div><div><p>{t(*detail[i][:2])}</p><p class="journey-note">{t(*detail[i][2:])}</p></div></article>' for i,(fr,en,dfr,den) in enumerate(g['STEPS']))+'</section>'
    journey+=split('hero-pool.webp',t('Prix & paiement','Price & payment'),t('Savoir ce qui est prévu.<br><em>Avant d’avancer.</em>','Know what is planned.<br><em>Before moving forward.</em>'),para(('Le prix de départ correspond à la configuration Carte Blanche. Les options d’aménagement, les frais liés à l’acquisition et les modalités de paiement doivent figurer dans une proposition détaillée.','The starting price corresponds to the Carte Blanche specification. Furnishing options, acquisition costs and payment terms should appear in a detailed proposal.'),('Virement en euros ou en bahts, ou paiement en cryptomonnaies via des prestataires spécialisés : les possibilités, les frais et les conditions sont à confirmer pour chaque projet.','Bank transfer in euros or baht, or cryptocurrency payment through specialist providers: availability, fees and conditions are confirmed for each project.')),link(t('Consulter les questions fréquentes','Read the frequently asked questions'),'faq.html'))+cta()
    add('parcours',t('Le parcours d’achat','Your buying journey'),t('Cinq étapes : échange, visite, cadre juridique, construction suivie et remise des clés.','Five steps: conversation, visit, legal framework, construction follow-up and receiving the keys.'),journey,False)

    village=hero(t('Prochain programme · Sud de Koh Samui','Upcoming development · Southern Koh Samui'),'Thong Krut<br><em>Village.</em>',t('L’esprit d’un village. La liberté de votre maison. Un programme résidentiel en préparation dans le sud de l’île.','The spirit of a village. The freedom of your own home. A residential development taking shape in the south of the island.'),'thongkrut.webp')
    village+=f'<section class="section intro-section"><div><p class="eyebrow">{t("Un nouveau projet Latitude","A new Latitude project")}</p><h2>{t("Une adresse commune.<br><em>Des vies singulières.</em>","One shared address.<br><em>Individual lives.</em>")}</h2></div><div class="intro-copy">'+para(('Thong Krut Village explore une autre échelle : un ensemble d’environ vingt lots, avec une cohérence architecturale et des maisons pensées pour un quotidien tropical.','Thong Krut Village explores a different scale: a development of around twenty plots, with architectural consistency and homes designed for tropical everyday life.'),('Le programme est en préparation. Les plans, surfaces, prestations et dates seront détaillés au lancement. Nous pouvons dès maintenant échanger sur vos attentes.','The development is in preparation. Plans, floor areas, specifications and dates will be detailed at launch. We can already discuss your expectations.'))+f'<div class="village-price"><small>{t("Prix de départ envisagé","Indicative starting price")}</small><strong>{t("215 000 €","€215,000")}</strong><p>{t("À confirmer lors du lancement, selon le lot et la configuration.","To be confirmed at launch, depending on the plot and specification.")}</p></div>{contact(t("Être informé du programme","Ask about the development"),"contact","Thong Krut Village")}</div></section>'
    village+=split('beach.webp',t('Le sud, autrement','The south, differently'),t('Retrouver<br><em>le rythme de l’île.</em>','Rediscover<br><em>the island’s rhythm.</em>'),para(('Le projet s’inscrit dans l’esprit du sud de Samui : un environnement villageois, la mer et une vie plus paisible. Lors de notre échange, nous vous présenterons le secteur et l’avancement du programme.','The project draws on the spirit of southern Samui: a village setting, the sea and a quieter way of life. During our conversation, we will introduce the area and the development’s progress.')),link(t('Découvrir Koh Samui','Discover Koh Samui'),'koh-samui.html'))+cta()
    add('thong-krut-village','Thong Krut Village',t('Programme résidentiel en préparation dans le sud de Koh Samui.','A residential development in preparation in southern Koh Samui.'),village)

    faq_groups=[
      ('projet','Le projet','The project',[
       ('Qu’est-ce que Latitude Samui ?','What is Latitude Samui?','Nous développons une collection limitée de villas à Koh Samui. Notre équipe coordonne le projet, la construction et la relation avec le futur propriétaire, avec les professionnels concernés.','We develop a limited collection of villas in Koh Samui. Our team coordinates the project, construction and relationship with the future owner, alongside the relevant professionals.'),
       ('Où se situent les villas ?','Where are the villas located?','Sabai, Suk, Jai et Baan Sawan se situent dans le secteur de Lamai. Thong Krut Village est un programme en préparation dans le sud de l’île.','Sabai, Suk, Jai and Baan Sawan are in the Lamai area. Thong Krut Village is a development in preparation in the south of the island.'),
       ('Puis-je visiter depuis l’étranger ?','Can I visit from abroad?','Oui, une présentation vidéo permet de découvrir le projet et de poser vos questions à distance. Une visite sur place peut ensuite être organisée selon vos disponibilités.','Yes, a video presentation lets you explore the project and ask questions remotely. An in-person visit can then be arranged around your availability.')]),
      ('acquisition','L’acquisition','Buying',[
       ('Quel cadre pour un acheteur étranger ?','What framework applies to an overseas buyer?','Le cadre d’acquisition dépend de la situation de l’acheteur et du projet. Nous organisons les échanges avec les avocats pour clarifier les droits proposés, les contrats et les vérifications préalables avant toute décision.','The acquisition framework depends on the buyer’s situation and the project. We arrange discussions with lawyers to clarify the proposed rights, contracts and due diligence before any decision.'),
       ('Quels documents examiner avant de s’engager ?','What documents should I review before committing?','Les documents fonciers, les autorisations, les plans, le descriptif des prestations, les contrats et les modalités financières font partie des éléments à examiner avec les professionnels compétents. Le dossier dépend du projet.','Land documents, permissions, plans, specifications, contracts and financial terms are among the items to review with the appropriate professionals. The file depends on the project.'),
       ('L’achat inclut-il un droit de séjour ?','Does buying include a right to stay?','Les questions d’acquisition et de séjour se préparent séparément. Pour votre installation, nous pouvons vous orienter vers un spécialiste afin d’étudier votre situation.','Acquisition and residency are planned separately. For your move, we can direct you to a specialist to review your situation.')]),
      ('construction','La construction','Construction',[
       ('Quel est le calendrier de construction ?','What is the construction timeline?','Les fiches Baan Sawan, Suk et Jai présentent une durée indicative de 12 à 18 mois. Sabai affiche une livraison estimée au quatrième trimestre 2028. Le calendrier propre à votre projet est à confirmer dans la proposition et les documents contractuels.','The Baan Sawan, Suk and Jai listings show an indicative 12–18-month construction period. Sabai shows an estimated delivery in the fourth quarter of 2028. Your project’s schedule must be confirmed in the proposal and contractual documents.'),
       ('Que puis-je personnaliser ?','What can I personalise?','Les fiches villas permettent de choisir une collection intérieure — Carte Blanche, Éveil des Sens ou Art de Vivre — et une approche paysagère. Les autres adaptations sont étudiées selon leur faisabilité et font l’objet d’un chiffrage.','Villa pages let you select an interior collection — Carte Blanche, Éveil des Sens or Art de Vivre — and a landscaping approach. Other changes are assessed for feasibility and quoted individually.'),
       ('Comment suivre le chantier à distance ?','How do I follow construction remotely?','L’équipe organise des points d’avancement et partage des photographies. Les modalités et la fréquence des échanges sont définies ensemble pour garder une vision claire des étapes.','The team organises progress updates and shares photographs. The format and frequency of communication are agreed together to keep a clear view of the stages.'),
       ('Quelles garanties sont prévues ?','What warranties are provided?','Les garanties, leur périmètre, leur durée et leurs conditions sont à vérifier dans les documents contractuels de votre villa. Nous vous présentons ces éléments avant engagement.','Warranties, their scope, duration and conditions must be checked in your villa’s contractual documents. We explain these elements before any commitment.')]),
      ('budget','Le budget & le paiement','Budget & payment',[
       ('Quel est le prix de départ ?','What is the starting price?','Les villas Sabai, Suk et Jai sont présentées à partir de 510 000 €, et Baan Sawan à partir de 805 000 €, en configuration Carte Blanche. Le prix envisagé pour Thong Krut Village débute à 215 000 €, à confirmer au lancement.','Sabai, Suk and Jai are listed from €510,000, and Baan Sawan from €805,000, in the Carte Blanche specification. Thong Krut Village has an indicative starting price of €215,000, to be confirmed at launch.'),
       ('La villa est-elle livrée meublée ?','Is the villa delivered furnished?','Carte Blanche comprend une villa achevée et équipée, sans mobilier ni décoration. Éveil des Sens et Art de Vivre ajoutent différents niveaux d’ameublement et d’aménagement, chiffrés sur devis.','Carte Blanche includes a completed, equipped villa, without furniture or decoration. Éveil des Sens and Art de Vivre add different furnishing and interior design levels, quoted separately.'),
       ('Quels frais prévoir en plus ?','What additional costs should I plan for?','Les frais juridiques, les frais et taxes liés à l’acquisition, les options choisies et les charges d’exploitation doivent être détaillés pour votre situation. Demandez une proposition complète avant de comparer les budgets.','Legal costs, acquisition fees and taxes, chosen options and running costs should be detailed for your situation. Request a complete proposal before comparing budgets.'),
       ('Comment s’organisent les paiements ?','How are payments organised?','L’échéancier et les conditions sont définis au contrat, en lien avec les étapes du projet. Les virements en euros ou en bahts et les paiements crypto via des prestataires spécialisés sont étudiés selon les modalités de chaque opération.','The schedule and terms are defined in the contract in relation to project milestones. Transfers in euros or baht and crypto payments through specialist providers are considered according to each transaction’s terms.')]),
      ('apres','Après la livraison','After handover',[
       ('Pouvez-vous organiser l’entretien ?','Can you arrange maintenance?','Des prestations de jardin, de piscine, de maintenance ou de conciergerie peuvent être organisées avec des partenaires locaux. Leur périmètre et leur coût sont définis séparément.','Garden, pool, maintenance and concierge services can be arranged with local partners. Their scope and cost are defined separately.'),
       ('Et si je souhaite louer ma villa ?','What if I want to rent out my villa?','La gestion locative peut être étudiée avec des partenaires spécialisés. Le projet doit tenir compte de l’usage autorisé, des coûts de gestion, de la saisonnalité et de votre présence personnelle. Aucun rendement n’est garanti.','Rental management can be discussed with specialist partners. The project should account for permitted use, management costs, seasonality and your own stays. No return is guaranteed.')])]
    faq=hero(t('Questions fréquentes','Frequently asked questions'),t('Les bonnes questions.<br><em>Des réponses claires.</em>','Good questions.<br><em>Clear answers.</em>'),t('Le projet, l’achat, les finitions et la vie après la livraison. Les premiers repères pour préparer notre échange.','The project, acquisition, finishes and life after handover. A starting point for our conversation.'))
    faq+=f'<section class="section faq-layout"><nav class="faq-nav" aria-label="{t("Thèmes des questions","Question topics")}">'+''.join(f'<a href="#{slug}">{t(fr,en)}</a>' for slug,fr,en,qs in faq_groups)+'</nav><div class="faq-groups">'
    for slug,fr,en,qs in faq_groups:
        faq+=f'<section id="{slug}"><h2>{t(fr,en)}</h2>'+''.join(f'<details class="faq-item"><summary>{t(qfr,qen)}<span aria-hidden="true">+</span></summary><p>{t(afr,aen)}</p></details>' for qfr,qen,afr,aen in qs)+'</section>'
    faq+='</div></section>'+cta(t('Une question<br><em>plus personnelle ?</em>','A more<br><em>personal question?</em>'))
    add('faq',t('Questions fréquentes','Frequently asked questions'),t('Les réponses sur les villas, le budget, la construction et l’accompagnement.','Answers about the villas, budget, construction and support.'),faq,False)

    boutique=hero(t('L’art de vivre Latitude','The Latitude way of life'),t('Un peu de Samui.<br><em>Partout avec vous.</em>','A little of Samui.<br><em>Wherever you go.</em>'),t('L’univers Latitude se prolonge au-delà de la maison. Notre boutique de vêtements, accessoires et objets d’art de vivre est en préparation.','The Latitude world extends beyond the home. Our boutique of clothing, accessories and lifestyle objects is in preparation.'),'beach.webp')
    boutique+=f'<section class="section boutique-intro"><p class="eyebrow">{t("Ouverture prochaine","Opening soon")}</p><h2>{t("L’esprit de l’île,<br><em>dans les petites choses.</em>","The island spirit,<br><em>in the little things.</em>")}</h2><p>{t("Des pièces inspirées de Koh Samui, de ses villages et de son quotidien. La collection et les modalités de commande seront présentées à l’ouverture.","Pieces inspired by Koh Samui, its villages and everyday life. The collection and ordering details will be presented at launch.")}</p><div class="boutique-words"><span>{t("Vêtements","Clothing")}</span><span>{t("Accessoires","Accessories")}</span><span>{t("Art de vivre","Lifestyle")}</span></div>{contact(t("Être informé de l’ouverture","Ask about the opening"),"contact","Boutique Latitude Samui")}{link(t("Continuer à explorer","Keep exploring"),"index.html")}</section>'
    add('boutique',t('La boutique','The boutique'),t('La boutique Latitude Samui est en préparation : vêtements, accessoires et art de vivre.','The Latitude Samui boutique is in preparation: clothing, accessories and lifestyle.'),boutique)

    cp=hero(t('Nous contacter','Contact us'),t('Votre projet commence<br><em>par un échange.</em>','Your project begins<br><em>with a conversation.</em>'),t('Vous découvrez l’île, vous comparez les villas ou vous avez déjà une idée précise ? Prenons le temps d’en parler.','Discovering the island, comparing villas or already have a clear idea? Let’s take the time to talk.'))
    cp+=f'<section class="section contact-page-grid"><div><p class="eyebrow">{t("L’équipe Latitude Samui","The Latitude Samui team")}</p><h2>{t("Une réponse<br><em>qui vous ressemble.</em>","A response<br><em>that’s personal to you.</em>")}</h2><a class="contact-email" href="mailto:contact@latitudesamui.com">contact@latitudesamui.com</a><div class="contact-location"><p class="eyebrow">{t("Nous retrouver","Find us")}</p><p>Bophut · Koh Samui · {t("Thaïlande","Thailand")}</p><p>{t("Rencontre sur rendez-vous ou échange à distance.","Meet by appointment or speak with us remotely.")}</p></div></div><div class="contact-intents">'
    intents=[('contact','Parler de mon projet','Discuss my project','Attentes, budget, calendrier : posons les premières bases.','Expectations, budget, timing: let’s start with the essentials.'),('brochure','Recevoir la brochure','Request the brochure','Les plans et les informations pour aller plus loin.','Plans and information to take the next step.'),('visit','Organiser une visite','Arrange a visit','Sur place à Koh Samui ou à distance en vidéo.','In person in Koh Samui or remotely by video.'),('estimate','Demander une estimation','Request an estimate','Une proposition adaptée à vos choix d’aménagement.','A proposal tailored to your furnishing choices.')]
    cp+=''.join(f'<article><div><h3>{t(fr,en)}</h3><p>{t(dfr,den)}</p></div>{contact(t("Commencer","Start"),intent,cls="intent-button",source="contact-page")}</article>' for intent,fr,en,dfr,den in intents)+'</div></section>'
    add('contact',t('Nous contacter','Contact us'),t('Parlez de votre projet avec Latitude Samui, demandez la brochure ou organisez une visite.','Discuss your project with Latitude Samui, request a brochure or arrange a visit.'),cp,False)

    privacy=hero(t('Vos informations','Your information'),t('Une relation<br><em>en toute simplicité.</em>','A straightforward<br><em>relationship.</em>'),t('Comment les informations saisies sur ce site sont utilisées.','How information entered on this site is used.'))
    privacy+='<section class="section prose">'+f'<h2>{t("Vos demandes","Your enquiries")}</h2>'+para(('Le parcours de contact prépare une demande avec les informations que vous saisissez : nom, coordonnées, message et, le cas échéant, villa et options choisies. Dans cette version, la demande est préparée pour votre messagerie. Elle n’est pas envoyée automatiquement.','The contact flow prepares an enquiry using the details you enter: name, contact information, message and, where relevant, villa and selected options. In this version, the enquiry is prepared for your email app. It is not sent automatically.'),('Si vous décidez de l’envoyer, Latitude Samui utilise ces informations pour vous répondre et suivre votre demande. Vous pouvez nous contacter à contact@latitudesamui.com pour toute question concernant vos informations.','If you choose to send it, Latitude Samui uses this information to reply and follow up on your enquiry. Contact contact@latitudesamui.com with any question about your information.'))+f'<h2>{t("Préférences sur votre appareil","Preferences on your device")}</h2>'+para(('Votre choix de langue est conservé sur votre navigateur. La sélection des collections peut être conservée pendant votre session pour retrouver votre configuration. Ces préférences ne sont pas transmises par le configurateur.','Your language choice is saved in your browser. Collection choices may be kept during your session so you can return to your configuration. These preferences are not transmitted by the configurator.'))+f'<h2>{t("Services externes","External services")}</h2>'+para(('Le site charge ses polices auprès de Google Fonts. Le chat Odoo se charge uniquement si vous activez la discussion. Les liens vers Google Maps et votre messagerie ouvrent des services externes, dont les propres règles s’appliquent.','The site loads its fonts from Google Fonts. The Odoo chat loads only when you activate it. Links to Google Maps and your email app open external services, which have their own terms.'))+f'<p>{t("Contact :","Contact:")} <a href="mailto:contact@latitudesamui.com">contact@latitudesamui.com</a></p></section>'
    add('confidentialite',t('Confidentialité','Privacy'),t('Informations sur le parcours de contact et les préférences de navigation.','Information about enquiries and browsing preferences.'),privacy,False)
    missing=hero('404',t('Un petit détour.<br><em>Retrouvons votre chemin.</em>','A small detour.<br><em>Let’s find your way.</em>'),t('Cette page n’existe pas ou a changé d’adresse.','This page does not exist or has moved.'))+f'<section class="section not-found">{link(t("Retour à l’accueil","Back to home"),"index.html","btn")}{link(t("Découvrir les villas","Explore the villas"),"villas.html")}</section>'
    add('404',t('Page introuvable','Page not found'),t('Retrouvez les villas Latitude Samui.','Return to the Latitude Samui villas.'),missing,False)
    return pages
